### PR TITLE
Added search device api

### PR DESCRIPTION
**Pull request by kk25q**
Ready for Review.

### CODE REVIEW

**Comment by kristinpeterson** [comment]
@sarahhenkens ready for review :)

**Comment by kk25q** [comment]
Ready for Review.

**Comment by majidabdul** [comment]
@kristinpeterson , @sarahhenkens: Can you please merge?  @attsdk has lost access to merge :(

**Comment by kristinpeterson** [comment]
@majidabdul sure thing!

@sarahhenkens when you have a moment can you merge and issue a new release?

**Pull request merged**
